### ISSUE TITLE
Do sdk support multisampling for Vulkan?

### ISSUE THREAD

**Issue by ChaithanyaSingamala** [powervr-graphics/Native_SDK#12]
I don't find any code related to multisampling in SDK for Vulkan. Does it support?

**Comment by senthuran-lkn** [comment]
yes there is an example in Intermediate/Multisampling. in order to do the multisampling you need to setup the pipeline(enabling mulstisample state), renderpass and the fbo.
the renderpass and the fbo have multi-sample attachment, this is where you render your scene and then you resolve the multisample image in to the final image where you present. 
hope that helps.

**Comment by ChaithanyaSingamala** [comment]
Thanks for information. I will make use of this.
I missed this because I was checking old.
