### ISSUE TITLE
linux armhf kernel module

### ISSUE THREAD

**Issue by sergey-suloev** [powervr-graphics/Native_SDK#23]
Hi, where can I find the driver source code ?

**Comment by senthuran-lkn** [comment]
Hi we don't provide driver source code.  Not sure what do you mean.

**Comment by sergey-suloev** [comment]
@senthuran-lkn  how can those user-space libraries be used on ARM platform without a kernel module ?

**Comment by senthuran-lkn** [comment]
sorry. Can you elaborate on what user space libraries are you talking about and the ARM platform  whether it is linux/ Android?

**Comment by sergey-suloev** [comment]
Ok, here I can see user-mode libraries 
https://github.com/powervr-graphics/Native_SDK/tree/5.0/Builds/Linux/armv7hf/Lib
What I am curious of is  where the kernel-mode counterpart source code can be found.

**Comment by senthuran-lkn** [comment]
Hi can you provide me the DDK version that you want the  kernal module source code for.

**Comment by senthuran-lkn** [comment]
Just for your curiosity those user module libraries that you pointed out are VFrame libraries. They are emulation libraries which runs Opengles on top of opengl ( platforms like desktop which doesn't support gles).The actual user module libraries can be found on the powervr devices therefore these emulation libraries are unnecessary. In order to provide the kernal module source code for the platform, we need to know what driver version does the platform has.

**Comment by sergey-suloev** [comment]
I am looking for GLESv2 (FB only, no need for X) support on allwinnner a31 which is in fact 4-core ARMv7 with integrated SGX544MP2

**Comment by senthuran-lkn** [comment]
can you run the following line which print out the driver version. and sent it back to us. 
sudo cat /proc/pvr/version

**Comment by sergey-suloev** [comment]
@senthuran-lkn 
My dear friend, I can't do what you asked me, because this my actual problem : I am missing a kernel module for SGX544MP2 on my platform! That was my inquiry and I was hoping you could help me find the source code for it!

**Comment by senthuran-lkn** [comment]
Hello, sorry for the confusion, the reason we ask that is that the Kernel module is tied to the kernel version and the user module. That's why you would usually start with a prebuilt image for the soc (that has a working driver) kernel, and do any modifications to the kernel module from that working starting point.

You can find the driver kernel module source code that is provided by Allwinner http://dl.linux-sunxi.org/SDK/A31/unpacked-stripped/a31_v4.5_hummingbird_kfb_ok/lichee/linux-3.3/modules/eurasia_km/
It is written against Linux-3.3

**Comment by senthuran-lkn** [comment]
The original SDK can be found here. 
http://linux-sunxi.org/A31#Original_SDKs

**Comment by sergey-suloev** [comment]
Ah, right, it is only for the old linux 3.x.
Thanks a lot.

**Comment by skyline20** [comment]
Did it work?

**Comment by sergey-suloev** [comment]
I am not using linux 3.x, so no, I haven't even tried it
