### ISSUE TITLE
FreeBSD Support

### ISSUE THREAD

**Issue by seanbruno** [powervr-graphics/Native_SDK#3]
Any chance of getting the needed libs built for FreeBSD here?  We'd like to bootstrap PowerVR for folks who want to do stuff/things on FreeBSD based hardware but can't really recommend it.

**Comment by JoeDavisIMG** [comment]
Hi Sean,

Are you referring to FreeBSD graphics drivers? Unfortunately, we cannot directly supply graphics drivers for our customers’ platforms. We deliver the source code of our reference driver to customers. It’s then their responsibility to integrate the driver and distribute binaries to their customers. If you would like to have FreeBSD compatible graphics drivers for a partiular piece of hardware, I'd recommend contacting the platform provider.

Thanks,
Joe

**Comment by seanbruno** [comment]
Oh no.  We (freebsd project) are working on the graphics driver.  I'm referring to the precompiled libs that are in the directories here:

https://github.com/powervr-graphics/Native_SDK/tree/3.5/Tools/OGLES/Build/Linux_armv7/ReleaseX11

**Comment by JoeDavisIMG** [comment]
Ah - thanks for the clarification. We include pre-compiled PVRTools libs as a convinience for the most popular operating systems that use our GPUs. I'm not familiar with FreeBSD, but you may be able to generate binaries with the Linux makefiles as-is or with a few modifications.

Our 4.0 SDK is due to be released soon and it's significantly different from the current code. If you're interested in helping us add FreeBSD support, I'd recommend waiting until the new code is available. We'd be happy to consider any pull requests sent to us :)

**Comment by JoeDavisIMG** [comment]
Hi Sean,

As of the 4.0 SDK, we no longer ship pre-compiled Framework libraries. I'll mark this issue as closed.

**Comment by einthusan** [comment]
@JoeDavisIMG do you know if FreeBSD support was ever added? Now with FreeBSD 13.0 official release having ARM64 supported as a Tier1 OS, it would be valuable for us to have PowerVR GE8320 drivers if we choose to boot the new FreeBSD OS to use with Vulkan. I believe FreeBSD is far more efficient with hardware resources than Linux.

Kindly suggest or point to more information on this! Thanks.
