### ISSUE TITLE
Warning "Vulkan is not supported on Apple platforms" when compiling it by AndroidStudio on MacOSX.

### ISSUE THREAD

**Issue by cylof22** [powervr-graphics/Native_SDK#34]
When compiling the example, the error says "Vulkan is not supported on Apple platforms". However, I am compiling the android version on MacOSX.

When compiling android version, the Vulkan library is provided by the Android NDK. It is not related to the host system.

**Comment by cylof22** [comment]
The error is reproduced for the VulkanHelloAPI. It can be fixed by add the following two lines to the CMakeLists.txt:

set (APPLE 0)
set(ANDROID 1)

**Comment by PVRDevTech** [comment]
Hi Cylof,

We have not attempted to build for Android on MacOS. However, this appears to be a CMake or even Android Studio bug. From the documentation of CMake: [https://cmake.org/cmake/help/v3.14/variable/APPLE.html](https://cmake.org/cmake/help/v3.14/variable/APPLE.html), it clearly states that APPLE should be set to true only when the *TARGET SYSTEM* is iOS, OSX etc.

Since your target system is Android, this variable should not have been set by CMake. I would at this point recommend working around the issue with a way similar to what you did.

You could also attempt do something like replacing the offending line (line 4 inVulkanHelloAPI) with if(APPLE and not ANDROID)

This appears to be a bug in either CMake itself or Android Studio (unlikely) - the variable APPLE should *not* be set just because you are running on OSX if your target is Android  (that would be the CMAKE_HOST_APPLE variable).

**Comment by cylof22** [comment]
Thanks for your reply. The workaround should be ok for me.
