### ISSUE TITLE
Is there any multithreading rendering example in v4.x ?

### ISSUE THREAD

**Issue by linuxaged** [powervr-graphics/Native_SDK#6]
I known there was a multithreading rendering example in v3.x, but it seems to be removed in v4.x
Is there any doc about how to deal with multithreading rendering with v4.x? Thanks!

**Comment by PVRDevTech** [comment]
Hello, in 3.5 there was indeed a demo that did asynchronous asset loading (rendering in one thread, loading assets in another), which we had to temporarily remove: because of the re-imagining of the SDK as a whole, a lot of examples we actually plan to keep did not make it to this release.
At the moment, we have the GnomeHorde example, which is multithreaded rendering via command buffer generation on separate threads, but it is for Vulkan, and it is a completely different scenario than asynchronous asset loading. (It does multi-threaded command buffer generation, something that might not really offer all that much of a benefit for OpenGL ES implementations).
We are planning to re-introduce a MultiThreaded-style (async asset loading) example for the next release.
Otherwise, you can still get it from the SDK 3.5 release.
