### ISSUE TITLE
In  VulkanBumpMap sample, textureView/sampler is destroyed after updating them into descriptorSet

### ISSUE THREAD

**Issue by zhuguoyu** [powervr-graphics/Native_SDK#7]
In this sample, both texture views and sampler objects are defines with local variables, while descriptorset is inside a deviceResource object. According to Vulkan spec 2.3.1. Object Lifetime, 
"The following Vulkan objects can be destroyed when no command buffers using the object are executing: 
....
VkImageView.
...
VkSampler
..."
One of  the ways that command uses vkImageView and vkSampler is through descritorset, so I think destroying these objects before command buffer still refers to that, is not legal. 

Please help to check and if it's true, probably need fix the sample

**Comment by PVRDevTech** [comment]
Very good spot, thank you - you are of course completely correct as far as the Vulkan spec goes, but in this particular case only 50% correct.
**Short version:** The textures are fine as the assetManager keeps them alive, the samplers are unfortunately not OK at all.

**Details**
All Framework objects are reference counted, so any live reference to them is enough to keep them alive. It was the intent that our descriptor set would actually keep such references to objects it contained alive (in fact in OpenGL ES version of the SDK that's exactly what it does), but unfortunately this was never implemented for the Vulkan version, hence this bug. But the textures are kept alive by the assetManager regardless.

**Textures**
The **assetManager** (**AssetStore** class) which is used to load the textures (**getTextureWithCaching()**) into **TextureView**s (these indeed contain the Vulkan **VkImageView**) and the corresponding **TextureStore** (maps to the Vulkan **VkImage**), keeps them alive until explicitly removed, so you are completely safe in that count. Cheers for Reference counted objects - the fact that their "initial" definition is local has no effect on that. 
_If so inclined, you can realise this effect if you inspect the reference counting of the TextureViews: Just before exiting the function textureView.refCountEntry->count is **3** - One for the local variable, one for the **DescriptorSetUpdate descSetCreateInfo**, and one for the **assetManager**._

In fact, every time you call **getTextureWithCaching(...)** for the same filename you will be getting the same textures (increasing their refcounting) instead of loading them from disk.

The objects will then be freed on **releaseView()**, when calling **assetManager.releaseAll()**;

**Samplers**
Unfortunately, the same cannot be said of the Samplers - that is indeed a bug, and their scope must somehow be increase. The fix we intend to do for them is to pull the sampler objects out of local scope and into class scope - i.e. make them member variables of the DeviceResource class and replace all references to them with deviceResource->samplerBilinear etc.

We will do another release of the SDK shortly (within a few days), so I will add this fix there. That's when we'll also update this repository.

**Comment by zhuguoyu** [comment]
Thanks for your detail explanation. Expecting the fix in next release.
